export const GET_STREAM_LIST = "GET_STREAM_LIST";
export const GET_STREAM_BY_GAME = "GET_STREAM_BY_GAME";
export const GET_STREAM_BY_CHANNEL = "GET_STREAM_BY_CHANNEL";
export const GET_STREAM = 'GET_STREAM';

